inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1.3
  NewCops: enable
  Exclude:
    - db/**/*
    - tmp/**/*
    - vendor/**/*
    - bin/**/*
    - log/**/*
    - home/**/*
    - node_modules/**/*
    - bundle_cache/**/*

RSpec/AnyInstance:
  Enabled: true
  Exclude:
    - spec/models/user_document_spec.rb

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/CaseIndentation:
  Enabled: false

Layout/ClassStructure:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/SuppressedException:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Metrics/AbcSize:
  # The ABC size is a calculated magnitude, so this number can be an Integer or
  # a Float.
  Max: 25
  Exclude:
    - bin/**/*
    - app/models/adapters/*
    - app/models/notification_system/*

Metrics/BlockLength:
  CountComments: false  # count full line comments?
  Max: 25
  Exclude:
    - config/**/*
    - spec/**/*

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  CountComments: false  # count full line comments?
  Max: 200

# Avoid complex methods.
Metrics/CyclomaticComplexity:
  Max: 8
  Exclude:
    - bin/**/*
    - app/models/notification_system/*

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 24

Metrics/ModuleLength:
  CountComments: false  # count full line comments?
  Max: 200

Layout/LineLength:
  Max: 160
  # To make it possible to copy or click on URIs in the code, we allow lines
  # containing a URI to be longer than Max.
  AllowURI: true
  URISchemes:
    - http
    - https
  Exclude:
    - bin/**/*
    - config/**/*

Rails/HasManyOrHasOneDependent:
  Enabled: false

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: true

Metrics/PerceivedComplexity:
  Max: 12

Rails:
  Enabled: true

Rails/Delegate:
  Enabled: true

Rails/SaveBang:
  Enabled: false

Rails/OutputSafety:
  Enabled: true

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ReturnNil:
  Enabled: true

Style/RescueStandardError:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Layout/DotPosition:
  EnforcedStyle: leading

Layout/IndentationConsistency:
  EnforcedStyle: normal

Style/StringLiterals:
  EnforcedStyle: single_quotes

RSpec/MultipleExpectations:
  Max: 5
